from setuptools import setup, find_packages

setup(
    name='trustcall',
    version='1.0.0',
    description='Deepfake voice detection via neural vocoder artifact analysis',
    author='Akshat Agrawal',
    python_requires='>=3.8',
    packages=find_packages(exclude=['venv', 'outputs', 'data']),
    py_modules=[
        'augment',
        'asvspoof_dataset',
        'benchmark',
        'cross_eval',
        'ensemble',
        'eval',
        'explain',
        'main',
        'model',
        'predict_dataset',
        'train_rawnet',
        'visualize',
    ],
    install_requires=[
        'torch>=1.12.0',
        'librosa>=0.9.2',
        'numpy>=1.21.0',
        'scipy>=1.7.0',
        'scikit-learn>=1.0.0',
        'matplotlib>=3.5.0',
        'pyyaml>=6.0',
        'tqdm>=4.64.0',
        'streamlit>=1.20.0',
        'soundfile>=0.11.0',
    ],
    entry_points={
        'console_scripts': [
            'trustcall-train=main:main',
            'trustcall-eval=eval:main',
            'trustcall-bench=benchmark:main',
            'trustcall-cross=cross_eval:main',
            'trustcall-explain=explain:main',
            'trustcall-predict=predict_dataset:main',
            'trustcall-visualize=visualize:main',
            'trustcall-ensemble=ensemble:main',
        ],
    },
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Multimedia :: Sound/Audio :: Analysis',
    ],
)
